### ISSUE TITLE
[Tracking] Re-implement existing `bevy_audio` examples

### ISSUE THREAD

**Issue by SolarLiner** [SolarLiner/bevy-kira-components#13]
# Summary

Re-implementing examples is a good smoke test for feature-parity with the existing `bevy_audio` plugin.

- [x] [audio.rs](https://github.com/bevyengine/bevy/blob/main/examples/audio/audio.rs) #17 
- [x] [audio_control.rs](https://github.com/bevyengine/bevy/blob/main/examples/audio/audio_control.rs) #9 
- [x] [decodable.rs](https://github.com/bevyengine/bevy/blob/main/examples/audio/decodable.rs) -> rename to "custom_sound" #17 
- [ ] [pitch.rs](https://github.com/bevyengine/bevy/blob/main/examples/audio/pitch.rs)
- [ ] [soundtrack.rs](https://github.com/bevyengine/bevy/blob/main/examples/audio/soundtrack.rs)
- [ ] [spatial_audio_2d.rs](https://github.com/bevyengine/bevy/blob/main/examples/audio/spatial_audio_2d.rs)
- [ ] [spatial_audio_3d.rs](https://github.com/bevyengine/bevy/blob/main/examples/audio/spatial_audio_3d.rs)
